name: ${GLOBAL_NAME}

services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: ${POSTGRES_IMAGE_NAME}:${POSTGRES_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TIMEZONE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - default:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}

  keycloak:
    container_name: ${KEYCLOAK_CONTAINER_NAME}
    image: ${KEYCLOAK_IMAGE_NAME}:${KEYCLOAK_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: ${POSTGRES_DATABASE}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_METRICS_ENABLED: ${KEYCLOAK_METRICS_ENABLED}
      KC_LOG_LEVEL: ${KEYCLOAK_LOG_LEVEL}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      TZ: ${TIMEZONE}
    ports:
      - ${KEYCLOAK_HTTP_PORT}:8080
    volumes:
      - keycloak_themes:/opt/keycloak/themes
    networks:
      - default
    depends_on:
      - postgres
    command: ${KEYCLOAK_COMMAND}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}

networks:
  default:
    name: ${KEYCLOAK_CONTAINER_NAME}_network
    driver: bridge

volumes:
  default:
    name: ${POSTGRES_CONTAINER_NAME}_data
    driver: local
  keycloak_themes:
    name: ${KEYCLOAK_CONTAINER_NAME}_themes
    driver: local